name: ${project.artifactId}Bukkit
main: ${project.groupId}.bukkit.WoltlabAPIBukkit
version: ${project.version}
author: xXSchrandXx
description: ${project.artifactId}Bukkit
softdepend: []
api-version: 1.13